# Unified pipeline configuration defaults

# Pair analysis
MAX_LAG = 50
INFO_BINS = 10
N_SURROGATES = 100
OUTER_TRAIN_FRACTION = 0.75
INNER_TRAIN_FRACTION = 0.70
RANDOM_STATE = 0

# Predictive model
MODEL_MAX_LAG = 15
TEST_FRACTION = 0.25
MAX_STIM_FEATURES = 12

# Atlas integration
USE_ATLAS_KERNEL_BRANCH = True
ATLAS_WEIGHT = 0.20
